export interface City {
  he: string;
  en: string;
}

export const ISRAEL_CITIES: City[] = [
  { he: 'אור עקיבא', en: 'Or Akiva' },
  { he: 'אור יהודה', en: 'Or Yehuda' },
  { he: 'אזור', en: 'Azur' },
  { he: 'איכסל', en: 'Ikhsal' },
  { he: 'אלעד', en: 'Elad' },
  { he: 'אלמון', en: 'Almon' },
  { he: 'אשדוד', en: 'Ashdod' },
  { he: 'אשקלון', en: 'Ashkelon' },
  { he: 'עתרות', en: 'Atarot' },
  { he: 'באר שבע', en: 'Beersheba' },
  { he: 'בית שאן', en: 'Beit Shean' },
  { he: 'בית שמש', en: 'Beit Shemesh' },
  { he: 'ביתר עילית', en: 'Betar Illit' },
  { he: 'בנימינה גונן', en: 'Binyamina Gonen' },
  { he: 'בני ברק', en: 'Bnei Brak' },
  { he: 'בת ים', en: 'Bat Yam' },
  { he: 'גבעים', en: 'Gaviim' },
  { he: 'גבעתיים', en: 'Givatayim' },
  { he: 'גדרה', en: 'Gedera' },
  { he: 'גילה', en: 'Gila' },
  { he: 'גן יבנה', en: 'Gan Yavneh' },
  { he: 'גני אם', en: 'Ganei Am' },
  { he: 'גני תקווה', en: 'Ganei Tikva' },
  { he: 'גרנות', en: 'Granot' },
  { he: 'דימונה', en: 'Dimona' },
  { he: 'זכרון יעקב', en: 'Zichron Yaakov' },
  { he: 'חדרה', en: 'Hadera' },
  { he: 'חריש', en: 'Harish' },
  { he: 'חרש', en: 'Harash' },
  { he: 'חרות', en: 'Harut' },
  { he: 'חיפה', en: 'Haifa' },
  { he: 'הוד השרון', en: 'Hod HaSharon' },
  { he: 'הרצליה', en: 'Herzliya' },
  { he: 'טבריה', en: 'Tiberias' },
  { he: 'יאיר', en: 'Yair' },
  { he: 'יבנה', en: 'Yavneh' },
  { he: 'יהוד מונוסון', en: 'Yehud-Monosson' },
  { he: 'יקנעם', en: 'Yokneam' },
  { he: 'יקנעם עלית', en: 'Yokneam Illit' },
  { he: 'ירוחם', en: 'Yerucham' },
  { he: 'ירושלים', en: 'Jerusalem' },
  { he: 'כוכב יאיר', en: 'Kochav Yair' },
  { he: 'כפר בילו', en: 'Kfar Bilou' },
  { he: 'כפר חסידים א', en: 'Kfar Hasidim A' },
  { he: 'כפר חסידים ב', en: 'Kfar Hasidim B' },
  { he: 'כפר הנוער', en: 'Kfar HaNour' },
  { he: 'כפר יונה', en: 'Kfar Yona' },
  { he: 'כפר יצחק', en: 'Kfar Yitzhak' },
  { he: 'כפר נחיל', en: 'Kfar Nahil' },
  { he: 'כפר סבא', en: 'Kfar Saba' },
  { he: 'כפר סלד', en: 'Kfar Seld' },
  { he: 'כפר צקל', en: 'Kfar Tzel' },
  { he: 'כפר ויתקין', en: 'Kfar Vitkin' },
  { he: 'כרמיאל', en: 'Carmiel' },
  { he: 'לוד', en: 'Lod' },
  { he: 'מגדל העמק', en: 'Migdal HaEmek' },
  { he: 'מודיעין', en: 'Modiin' },
  { he: 'מודיעין מכבים רעות', en: 'Modiin Maccabee Reut' },
  { he: 'מודיעין עילית', en: 'Modiin Illit' },
  { he: 'מטולה', en: 'Metula' },
  { he: 'מצדה', en: 'Metzada' },
  { he: 'מעלה אדומים', en: 'Maaleh Adumim' },
  { he: 'מעלות תרשיחא', en: 'Maalot Tarshiha' },
  { he: 'מזכרת בתיה', en: 'Mizkeret Batya' },
  { he: 'מרכז שפירא', en: 'Merkaz Shapira' },
  { he: 'נהריה', en: 'Nahariya' },
  { he: 'נס ציונה', en: 'Nes Ziona' },
  { he: 'נתניה', en: 'Netanya' },
  { he: 'נתיב השיירה', en: 'Nativ HaShayara' },
  { he: 'נוה דנה', en: 'Noha Dana' },
  { he: 'עכו', en: 'Acre' },
  { he: 'עפולה', en: 'Afula' },
  { he: 'עמנואל', en: 'Emanuel' },
  { he: 'פתח תקווה', en: 'Petah Tikva' },
  { he: 'פרדס חנה כרכור', en: 'Pardes Hanna Karkur' },
  { he: 'קדימה', en: 'Kadima' },
  { he: 'קדימה צורן', en: 'Kadima Zoran' },
  { he: 'קצרין', en: 'Katzrin' },
  { he: 'קרית אונו', en: 'Kiryat Ono' },
  { he: 'קרית אל', en: 'Kiryat El' },
  { he: 'קרית אתא', en: 'Kiryat Ata' },
  { he: 'קרית ביאליק', en: 'Kiryat Bialik' },
  { he: 'קרית גת', en: 'Kiryat Gat' },
  { he: 'קרית יוביל', en: 'Kiryat Yovel' },
  { he: 'קרית יעם', en: 'Kiryat Yam' },
  { he: 'קרית מלאכי', en: 'Kiryat Malachi' },
  { he: 'קרית מוצקין', en: 'Kiryat Motzkin' },
  { he: 'קרית ספר', en: 'Kiryat Sefer' },
  { he: 'קרית שמונה', en: 'Kiryat Shmona' },
  { he: 'קיבוץ חוקוק', en: 'Kibbutz Hukok' },
  { he: 'קיבוץ טל גוש', en: 'Kibbutz Tel Gosh' },
  { he: 'רגבים', en: 'Ragavim' },
  { he: 'ראש העין', en: 'Rosh HaAyin' },
  { he: 'רעננה', en: 'Raanana' },
  { he: 'רמלה', en: 'Ramla' },
  { he: 'רמת גן', en: 'Ramat Gan' },
  { he: 'רמת השרון', en: 'Ramat HaSharon' },
  { he: 'ראשון לציון', en: 'Rishon LeZion' },
  { he: 'סח נויה', en: 'Sach Noia' },
  { he: 'סומך', en: 'Somekh' },
  { he: 'ספיר', en: 'Sapir' },
  { he: 'שלומי', en: 'Shlomi' },
  { he: 'שפרעם', en: 'Shfaram' },
  { he: 'צור יצחק', en: 'Tzur Yitzhak' },
  { he: 'צפת', en: 'Safed' },
  { he: 'צורים', en: 'Tzurim' },
  { he: 'תל אביב - יפו', en: 'Tel Aviv - Jaffa' },
  { he: 'תל מונד', en: 'Tel Mond' },
  { he: 'תל שבע', en: 'Tel Sheva' },
];
