/**
 * Global Component Styles
 * Reusable style objects for consistency across components
 */

import { COLORS, HOVER_COLORS } from './colors';

export const formStyles = {
  wrapper: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '3rem 2rem 4rem',
    textAlign: 'center' as const,
    position: 'relative' as const,
    overflow: 'hidden' as const,
  },
  header: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: '6rem',
    position: 'relative' as const,
    gap: '1.5rem',
    overflow: 'visible' as const,
  },
  logo: {
    fontSize: '1.2rem',
    fontWeight: 900,
    color: COLORS.darkGray,
    position: 'relative' as const,
    flex: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  logoImage: {
    width: '100%',
    maxWidth: '520px',
    height: 'auto',
    objectFit: 'contain',
  },
  title: {
    fontWeight: 700,
    lineHeight: 1.3,
    color: COLORS.darkGray,
    fontSize: '2.8rem',
    marginBottom: '1.5rem',
    letterSpacing: '-0.02em',
    cursor: 'default',
  },
  subtitle: {
    opacity: 0.75,
    marginBottom: '4rem',
    color: COLORS.darkGray,
    fontSize: '1.15rem',
    lineHeight: 1.5,
  },
  cards: {
    display: 'grid' as const,
    gap: '2rem',
    marginBottom: '5rem',
  },
  card: {
    padding: '1.5rem',
    borderRadius: 999,
    background: COLORS.white,
    cursor: 'pointer',
    border: `2px solid transparent`,
    transition: 'border-color 0.2s ease',
    '&:hover': {
      borderColor: COLORS.primary,
    },
  },
  form: {
    display: 'grid' as const,
    gap: '1rem',
    maxWidth: 520,
    margin: '0 auto',
  },
  label: {
    fontSize: '1rem',
    fontWeight: 500,
    color: COLORS.mediumGray,
    marginBottom: '0.15rem',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '0.9rem',
    borderRadius: '0.5rem',
    border: `2px solid #e0e0e0`,
    fontSize: '1.05rem',
    fontFamily: 'inherit',
    boxSizing: 'border-box' as const,
    transition: 'border-color 0.2s ease',
    '&:focus': {
      outline: 'none',
      borderColor: COLORS.primary,
    },
  },
  select: {
    width: '100%',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    border: `2px solid #e0e0e0`,
    fontSize: '1rem',
    fontFamily: 'inherit',
    backgroundColor: COLORS.white,
    cursor: 'pointer',
    transition: 'border-color 0.2s ease',
    '&:focus': {
      outline: 'none',
      borderColor: COLORS.primary,
    },
  },
  cta: {
    marginTop: '1.5rem',
    padding: '0.75rem',
    borderRadius: 999,
    border: 'none',
    color: COLORS.white,
    backgroundColor: COLORS.secondary,
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: HOVER_COLORS.secondaryHover,
    },
  },
  trust: {
    marginTop: '0.75rem',
    opacity: 0.6,
    fontSize: '0.8rem',
    color: COLORS.darkGray,
    textAlign: 'center' as const,
  },
  slogan: {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: COLORS.secondary,
    margin: '0.5rem auto 0',
    width: '100%',
    maxWidth: '500px',
    textAlign: 'center' as const,
  },
};
